prog:enigme2.o main.o 
	gcc enigme2.o main.o -o prog -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
main.o:main.c 
	gcc -c main.c 
enigme2.o:enigme2.c 
	gcc -c enigme2.c 
enigme.o:enigme.h
	gcc -c enigme2.h
